# Generated by Django 6.0.2 on 2026-02-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lang', models.CharField(max_length=20)),
                ('year_of_release', models.PositiveIntegerField()),
                ('imdb_rating', models.FloatField()),
            ],
        ),
    ]
