# Generated by Django 6.0.2 on 2026-02-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Cameron', max_length=50),
        ),
    ]
