# Generated by Django 6.0.2 on 2026-03-04 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
        migrations.CreateModel(
            name='SongArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.role')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.song')),
            ],
            options={
                'unique_together': {('person', 'song', 'role')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(through='movies_app.SongArtists', to='movies_app.person'),
        ),
    ]
