# Generated by Django 6.0.2 on 2026-02-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sales_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Lang', models.CharField(max_length=20)),
                ('Year_of_Release', models.PositiveIntegerField()),
            ],
        ),
    ]
