# Generated by Django 6.0.2 on 2026-02-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=55)),
                ('Price', models.FloatField()),
                ('Desc', models.CharField(max_length=10)),
            ],
        ),
    ]
