# Generated by Django 6.0.2 on 2026-02-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Quantity', models.PositiveIntegerField()),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
    ]
