# Generated by Django 6.0.2 on 2026-02-11 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='Name',
        ),
        migrations.AddField(
            model_name='sales',
            name='Product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
