# Generated by Django 6.0.2 on 2026-02-12 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_sales_name_sales_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
