# Generated by Django 6.0.2 on 2026-02-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(default=7),
            preserve_default=False,
        ),
    ]
