# Generated by Django 6.0.2 on 2026-02-12 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_movie_imdb_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOfficeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.movie')),
            ],
        ),
    ]
